[phases.setup]
nixPkgs = ["tesseract", "poppler_utils"]
aptPkgs = ["libgl1-mesa-dri", "libglib2.0-0"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app:socketio --timeout 300 --keep-alive 2 --max-requests 1000 --max-requests-jitter 100 --preload"